Repository KushAhuja02/ROCK-PAPER-SCISSOR, pull requests merged in 2023-05, with the labels that each got.

#3 Improved README.md file
  README.md
Labels: enhancement, hackodex2023, hackodex-accepted

#5 Added CONTRIBUTION.md file
  CONTRIBUTION.md
Labels: hackodex2023, hackodex2023-accepted

#7 Added Dark Mode Button
  index.css
  index.html
  index.js
Labels: hackodex2023, hackodex-accepted

#9 Make changes in icons in dark mode
  index.css
  index.html
  index.js
Labels: hackodex2023, hackodex-accepted
